### PR TITLE
In 218 refactor generate g2t

### LINKED ISSUE #8: Needs to be updated to handle the VEP GFF
The manual still states that generate_g2t is used to create the genes2transcripts files.
The code in the test directory parser (https://github.com/eastgenomics/test_directory_parser/blob/main/test_directory_parser/transcript_assigner.py) needs to be moved to this repo so that we can use that repo as the source of all things g2t related.

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Complete refactoring of code

- Conversion of gene symbols to HGNC ids
- Assignment of transcripts using MANE Select and HGMD (Fixes #8)

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[`main.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY355RI-q5wZNz2O7j6:-NY355RI-q5wZNz2O7j7:bh6hauq) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/main.py#L22)):*
> ```Python
>         convert_symbols.write_hgnc_ids(hgnc_ids, output_path)
> 
>     elif args["command"] == "assign_transcripts":
> ```

can there be a check for args.command where the command is neither convert_symbols & assign_transcripts. thus the script will print the acceptable commands
___
*[`README.md` line 7 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY310gK3JNmmIkWs0AZ:-NY310gK3JNmmIkWs0A_:bmsaexq) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/README.md#L7)):*
> ```Markdown
> To run this code, you need to have:
> 
> - A HGNC dump downloaded from https://www.genenames.org/download/custom/
> ```

what columns to tick for hgnc or default?
___
*[`README.md` line 45 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY30viT1YhhLtv4o0tx:-NY30viT1YhhLtv4o0ty:b-jiefg7) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/README.md#L45)):*
> ```Markdown
> 
> python main.py --hgnc_dump ${hgnc_dump} convert_symbols -symbols ${symbol} ${symbol} ...
> python main.py --hgnc_dump ${hgnc_dump} convert_symbols -symbol_file ${symbol_file}
> ```

what format should the symbol file have? txt, csv etc.



_Code quote:_
```Markdown
${symbol_file}
```
___
*[`README.md` line 48 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY35Mpg1Po-D5aKpS7N:-NY35Mpg1Po-D5aKpS7O:bpmgrj0) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/README.md#L48)):*
> ```Markdown
> 
> python main.py --hgnc_dump ${hgnc_dump} assign_transcripts -mane ${MANE_Select_file} -hgmd ${database_name} ${database_usr} ${database_pwd} -hgnc_ids ${hgnc_id} ${hgnc_id} ...
> python main.py --hgnc_dump ${hgnc_dump} assign_transcripts -mane ${MANE_Select_file} -hgmd ${database_name} ${database_usr} ${database_pwd} -hgnc_file ${hgnc_file}
> ```

what format should the hgnc file be e.g. columns etc
___
*[`g2t_ops/utils.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY34R7CAV9i63m-3paX:-NY34R7CAV9i63m-3paY:bc1jm0t) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/utils.py#L86)):*
> ```Python
> 
> 
> def parse_exon_file(dnanexus_file_id):
> ```

shouldn't this be dnanexus_ids since it contain both project-id and file-id

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @Yu-jinKim)

___
*[`g2t_ops/transcript_assigner.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY35YU01fIhZyHqIE1p:-NY35YU01fIhZyHqIE1q:b-909cun) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/transcript_assigner.py#L8)):*
> ```Python
> 
> 
> def get_date_for_db():
> ```

can there be type hint e.g. `get_date_for_db() -> datetime.datetime`
will make future reading easier
___
*[`g2t_ops/transcript_assigner.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY35gDy1jKzlHG7iNUf:-NY35gDy1jKzlHG7iNUg:b-i411qm) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/transcript_assigner.py#L18)):*
> ```Python
> 
> 
> def parse_mane_file(mane_file, hgnc_dump):
> ```

type hinting for all other functions too e.g. `def parse_mane_file(mane_file: str, hgnc_dump: dict) -> dict`

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @JasonLing95)

___
*[`main.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY355RI-q5wZNz2O7j6:-NYINl5d9_qaewlFqb9w:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/main.py#L22)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

can there be a check for args.command where the command is neither convert_symbols & assign_transcripts. thus the script will print the acceptable commands
</blockquote></details>

Done.
___
*[`README.md` line 7 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY310gK3JNmmIkWs0AZ:-NYINkQs5YkQZcKxUGkx:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/README.md#L7)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

what columns to tick for hgnc or default?
</blockquote></details>

Done.
___
*[`README.md` line 45 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY30viT1YhhLtv4o0tx:-NYINjxE5fYI4o4kzqRw:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/README.md#L45)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

what format should the symbol file have? txt, csv etc.
</blockquote></details>

Done.
___
*[`README.md` line 48 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY35Mpg1Po-D5aKpS7N:-NYINjaF1eRYey_ngPmI:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/README.md#L48)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

what format should the hgnc file be e.g. columns etc
</blockquote></details>

Done.
___
*[`g2t_ops/transcript_assigner.py` line 8 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY35YU01fIhZyHqIE1p:-NYINizh1iaBgAMvjU_Y:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/transcript_assigner.py#L8)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

can there be type hint e.g. `get_date_for_db() -> datetime.datetime`
will make future reading easier
</blockquote></details>

Done.
___
*[`g2t_ops/transcript_assigner.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY35gDy1jKzlHG7iNUf:-NYINicy8lIwZ9693LVf:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/transcript_assigner.py#L18)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hinting for all other functions too e.g. `def parse_mane_file(mane_file: str, hgnc_dump: dict) -> dict`
</blockquote></details>

Done.
___
*[`g2t_ops/utils.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY34R7CAV9i63m-3paX:-NYIN_r_2wMXaR-fEFDL:bib4apa) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/utils.py#L86)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

shouldn't this be dnanexus_ids since it contain both project-id and file-id
</blockquote></details>

Not sure i understand

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[`g2t_ops/utils.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY34R7CAV9i63m-3paX:-NYIQF6d1h0d7W76rpps:b7bb12x) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/utils.py#L86)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Not sure i understand
</blockquote></details>

the `dnanexus_file_id` is not purely file-ids but more of project-id:file-id thus the naming of the variable should be more reflective of it content e.g. dnanexus_ids

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @JasonLing95)

___
*[`g2t_ops/utils.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NY34R7CAV9i63m-3paX:-NYIopufCwn7c5AHTIhq:b-896fix) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/84faaa2bce7f669c0acf7ac0acbd2fa22bd6ea8b/g2t_ops/utils.py#L86)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the `dnanexus_file_id` is not purely file-ids but more of project-id:file-id thus the naming of the variable should be more reflective of it content e.g. dnanexus_ids
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`README.md` line 41 at r3](https://reviewable.io/reviews/eastgenomics/g2t_ops/9#-NYIztL_Eka6ikSW4erp:-NYIzcthDWkB2zHC4Ke-:b7d28uf) ([raw file](https://github.com/eastgenomics/g2t_ops/blob/e3681d7143597b5639b569b4f84acf86f6d14db9/README.md#L41)):*
> ```Markdown
> ## How to run
> 
> The symbol file and hgnc files are single column files with a single element per row.
> ```

example will be nice

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/g2t_ops/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
