### PR TITLE
initial push

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/generate_g2t/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/generate_g2t/1)* status: all files reviewed, 7 unresolved discussions (waiting on @Yu-jinKim)

___
*[g2t.py, line 143 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjmcfJ4PYb54f2wuWs:-MUjmcfJ4PYb54f2wuWt:b-gzurpy) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L143)):*
> ```Python
> 
> 
> def find_id_using_ensg(ensg_id, hgnc_data):
> ```

docstring missing
___
*[g2t.py, line 157 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjmrrJ9mof4NbpT9ga:-MUjmrrJ9mof4NbpT9gb:bjfe3dj) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L157)):*
> ```
> file
> ```
filepath?
___
*[g2t.py, line 201 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjnaAnEah1UM6HS41i:-MUjnaAnEah1UM6HS41j:bd1pe1t) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L201)):*
> ```
> if hgnc_id is None:
> ```
What's the scenario here? Do some genes have no ENSG in the gff?
___
*[g2t.py, line 253 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjnscKDTo9KC-NiW6b:-MUjnscKDTo9KC-NiW6c:b-enmvhi) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L253)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>     if gene_symbol in hgnc_data:
>         hgnc_id = hgnc_data[gene_symbol]["hgnc_id"]
>         ensg_id = hgnc_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in alias_data:
>         hgnc_id = alias_data[gene_symbol]["hgnc_id"]
>         ensg_id = alias_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in prev_data:
>         hgnc_id = prev_data[gene_symbol]["hgnc_id"]
>         ensg_id = prev_data[gene_symbol]["ensg_id"]
>     return hgnc_id, ensg_id
> ```
</details>

Is this robust to cases where the same symbol has been used for multiple genes?

If a symbol is in hgnc_data and alias_data, how do we know which is correct?
___
*[g2t.py, line 340 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjofoKAsVG3wi1i4xd:-MUjofoKAsVG3wi1i4xe:bpqf0o0) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L340)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             if "partial" in final_check:
>                 clinical_transcript = [
>                     tx
>                     for tx in transcript_data
>                     if transcript_data[tx]["match"] == "partial"
>                 ][0]
> ```
</details>

If we have multiple partial matches will this always select the most recent version?
e.g. partial contains [NM_00001.1,NM_00001.2]
Correct option is NM_00001.2
___
*[g2t.py, line 370 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjlqm-01xUD_0_4I8Z:-MUjlqm-01xUD_0_4I8_:b-4sqdt2) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L370)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> def get_header_index(header_name: str, headers: list):
>     """ Get the index of a given header
>     Args:
>         header_name (str): Header name
>         headers (list): List of headers
>     Returns:
>         int: Index for given header name
>     """
>     return [
>         i
>         for i, ele in enumerate(headers)
>         if ele == header_name
>     ][0]
> ```
</details>


This can also be achieved by
```
headers.index(header_name)
```
___
*[g2t.py, line 572 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjpx0W-0zSYu8vmWk8:-MUjpx0W-0zSYu8vmWk9:b-ghacfo) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L572)):*
> ```
> "hgmd_2020_3"
> ```
Should this be an arg so that we can update when new versions are released without requiring changes to the code?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/generate_g2t/1)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[g2t.py, line 143 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjmcfJ4PYb54f2wuWs:-MUnWp151dmACBytIsYb:b-896fix) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L143)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

docstring missing
</blockquote></details>

Done.
___
*[g2t.py, line 157 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjmrrJ9mof4NbpT9ga:-MUnWo_p7lNtXILoDxAa:b-896fix) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L157)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> file
> ```
filepath?
</blockquote></details>

Done.
___
*[g2t.py, line 201 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjnaAnEah1UM6HS41i:-MUnMJEC0S52aM4sLykG:b-rp1dsm) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L201)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> if hgnc_id is None:
> ```
What's the scenario here? Do some genes have no ENSG in the gff?
</blockquote></details>

if the ensg is not present in the HGNC file so most probably a GRCh37 ENSG 
___
*[g2t.py, line 253 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjnscKDTo9KC-NiW6b:-MUnNHIi8RlpkYtHb_I4:b-e30hbf) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L253)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     if gene_symbol in hgnc_data:
>         hgnc_id = hgnc_data[gene_symbol]["hgnc_id"]
>         ensg_id = hgnc_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in alias_data:
>         hgnc_id = alias_data[gene_symbol]["hgnc_id"]
>         ensg_id = alias_data[gene_symbol]["ensg_id"]
>     elif gene_symbol in prev_data:
>         hgnc_id = prev_data[gene_symbol]["hgnc_id"]
>         ensg_id = prev_data[gene_symbol]["ensg_id"]
>     return hgnc_id, ensg_id
> ```
Is this robust to cases where the same symbol has been used for multiple genes?

If a symbol is in hgnc_data and alias_data, how do we know which is correct?
</blockquote></details>

there's a priority in the assignment, hgnc_data contains the primary symbol, alias data the aliases and prev is the previous symbol
___
*[g2t.py, line 340 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjofoKAsVG3wi1i4xd:-MUnWnNs-JcAdx-m93GV:b-896fix) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L340)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>             if "partial" in final_check:
>                 clinical_transcript = [
>                     tx
>                     for tx in transcript_data
>                     if transcript_data[tx]["match"] == "partial"
>                 ][0]
> ```
If we have multiple partial matches will this always select the most recent version?
e.g. partial contains [NM_00001.1,NM_00001.2]
Correct option is NM_00001.2
</blockquote></details>

Done.
___
*[g2t.py, line 370 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjlqm-01xUD_0_4I8Z:-MUnWmyQ3jnY9-oK-h2S:b-896fix) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L370)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> def get_header_index(header_name: str, headers: list):
>     """ Get the index of a given header
>     Args:
>         header_name (str): Header name
>         headers (list): List of headers
>     Returns:
>         int: Index for given header name
>     """
>     return [
>         i
>         for i, ele in enumerate(headers)
>         if ele == header_name
>     ][0]
> ```

This can also be achieved by
```
headers.index(header_name)
```
</blockquote></details>

Done.
___
*[g2t.py, line 572 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjpx0W-0zSYu8vmWk8:-MUnWm_lCjdIsz9VxriS:b-896fix) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L572)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> "hgmd_2020_3"
> ```
Should this be an arg so that we can update when new versions are released without requiring changes to the code?
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/generate_g2t/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[g2t.py, line 253 at r3](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MUjnscKDTo9KC-NiW6b:-MV2-tnw69wgHI_s_YKu:b-1oudhn) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/51475d1157451dea5ada13d73ded1ba7fd153fb5/g2t.py#L253)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

there's a priority in the assignment, hgnc_data contains the primary symbol, alias data the aliases and prev is the previous symbol
</blockquote></details>

OK, suffix applied to flag ambiguous symbols for manual intervention
___
*[g2t.py, line 623 at r5](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MV2-Obk9VD8c91nIH64:-MV2-Obk9VD8c91nIH65:bbeyrjs) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/3f12c6beb0a6ec9150aa92e6092b70752fffb3ae/g2t.py#L623)):*
> ```
> if hgnc_id.endswith("TBD"):
> ```
Matches an imaginary gene called ATBD.
Could include the delimiter in the string to fix this i.e. `_TBD`

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/generate_g2t/1)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[g2t.py, line 623 at r5](https://reviewable.io/reviews/eastgenomics/generate_g2t/1#-MV2-Obk9VD8c91nIH64:-MVRI3ydBmmbJskpvxv0:b-896fix) ([raw file](https://github.com/eastgenomics/generate_g2t/blob/3f12c6beb0a6ec9150aa92e6092b70752fffb3ae/g2t.py#L623)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> if hgnc_id.endswith("TBD"):
> ```
Matches an imaginary gene called ATBD.
Could include the delimiter in the string to fix this i.e. `_TBD`
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/generate_g2t/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
